# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  name: Default
  demands:
   - agent.name -equals agentdevops


steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'npm install'

- script: |
    npm run build
  displayName: 'npm build'

- task: CopyFiles@2
  inputs:
    sourceFolder: '$(Build.SourcesDirectory)' # location of cloned code
    contents: |
       src/*
       public/*
    targetFolder: '$(Build.ArtifactStagingDirectory)' # intermidaiate location, before publishing artifacts
  displayName: 'Copy project files'

- task: PublishPipelineArtifact@1
  inputs:
    artifactName: e2e-server 
    targetPath: '$(Build.ArtifactStagingDirectory)' # get artifacts from intermidiate location 
    publishLocation: 'pipeline' # save it in azure pipeline instead of fileshare
  displayName: 'Publish npm artifact'